repos:
  # Only keep indexing maintenance locally; YAML & workflow linting handled in CI.
  - repo: local
    hooks:
      - id: reindex
        name: Rebuild lightweight indexes (repo-manifest.json)
        entry: bash scripts/reindex.sh
        language: system
        pass_filenames: false
        stages: [pre-commit]
        # Fast by design: scripts already exclude solutions/

# End of file
