name: Monitor actionlint support for workflows permission

on:
  schedule:
    - cron: '0 8 * * 1' # Weekly (Monday 08:00 UTC)
  workflow_dispatch:

permissions:
  contents: read
  issues: write

jobs:
  probe:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Download latest actionlint
        run: bash <(curl -s https://raw.githubusercontent.com/rhysd/actionlint/main/scripts/download-actionlint.bash)

      - name: Run actionlint WITHOUT ignore flag
        id: lint
        run: |
          set +e
          ./actionlint -color 2>&1 | tee actionlint_output.txt
          ec=$?
          if grep -q 'unknown permission scope "workflows"' actionlint_output.txt; then
            echo "still_unsupported=true" >> "$GITHUB_OUTPUT"
          else
            echo "still_unsupported=false" >> "$GITHUB_OUTPUT"
          fi
          # Always succeed; we only use status to decide issue creation.
          exit 0

      - name: Ensure maintenance label exists
        if: steps.lint.outputs.still_unsupported == 'false'
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          set -e
          if ! gh label list --limit 200 | grep -E '^maintenance\b' > /dev/null; then
            gh label create maintenance --color 0e8a16 --description 'Maintenance / chore tasks'
          fi

      - name: Create or update removal issue
        if: steps.lint.outputs.still_unsupported == 'false'
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          set -e
          title='chore: remove actionlint workflows permission workaround'
          body_file=issue_body.md
          cat > "$body_file" <<'EOF'
The scheduled probe indicates actionlint no longer errors on the `workflows` permission scope.

Please remove the temporary workaround:
1. Delete the -ignore 'unknown permission scope "workflows"' flag in `.github/workflows/lint-action.yml`.
2. Remove `sync-solution-choices.yml` from `.actionlintignore` (delete file if now empty).
3. Delete `docs/tracking/remove-actionlint-workflows-ignore.md`.
4. Clean up related comments in workflow files.

This issue was auto-generated by `monitor-actionlint-permission.yml`.
EOF
          existing=$(gh issue list --state open --search "$title" --json number --jq '.[0].number') || true
          if [ -z "$existing" ]; then
            gh issue create --title "$title" --body-file "$body_file" --label maintenance
          else
            gh issue comment "$existing" --body "Probe successful again on $(date -u +%F). Workaround still removable if not already done."
          fi

      - name: Log unsupported status
        if: steps.lint.outputs.still_unsupported == 'true'
        run: |
          echo "actionlint still does not recognize 'workflows' permission; no issue update." 
