name: Release action
# Call the reusable workflow release-solution-with-inputs.yml
# Release your solution to prod when you create a new release.

on:
  release:
    types: [published, prereleased]
  workflow_dispatch: {}

permissions:
  contents: write

jobs:
  check-pre-release:
    runs-on: ubuntu-latest
    outputs:
      is_prerelease: ${{ steps.get_release.outputs.is_prerelease }}
    steps:
      - name: Get release information
        id: get_release
        run: |
          echo "is_prerelease=$(jq -r .prerelease $GITHUB_EVENT_PATH)" >> $GITHUB_OUTPUT

  deploy-preprod:
    needs: check-pre-release
    if: needs.check-pre-release.outputs.is_prerelease == 'true'
    uses: ./.github/workflows/release-solution-to-prod-with-inputs.yml
    with:
      solution_name: ALMLab
    secrets:
      envSecret: ${{ secrets.POWERPLATFORMSPN }}
      BUILD_ENVIRONMENT_URL: ${{ secrets.ENVIRONMENTURL_DEV }}
      PRODUCTION_ENVIRONMENT_URL: ${{ secrets.ENVIRONMENTURL_PREPROD }}
      CLIENT_ID: ${{ secrets.POWERPLATFORM_APPID }}
      TENANT_ID: ${{ secrets.TENANTID }}

  deploy-prod:
    needs: check-pre-release
    if: needs.check-pre-release.outputs.is_prerelease == 'false'
    uses: ./.github/workflows/release-solution-to-prod-with-inputs.yml
    with:
      solution_name: ALMLab
    secrets:
      envSecret: ${{ secrets.POWERPLATFORMSPN }}
      BUILD_ENVIRONMENT_URL: ${{ secrets.ENVIRONMENTURL_DEV }}
      # Replace ENVIRONMENTURL_PROD with the actual secret name for your production environment.
      PRODUCTION_ENVIRONMENT_URL: ${{ secrets.ENVIRONMENTURL_PROD }}
      CLIENT_ID: ${{ secrets.POWERPLATFORM_APPID }}
      TENANT_ID: ${{ secrets.TENANTID }}
