name: Release action
# Call the reusable workflow release-solution-with-inputs.yml
# Release your solution to prod when you create a new release.

on:
  release:
    types: [prereleased, released]
  workflow_dispatch: {}

permissions:
  contents: write

jobs:
  check-pre-release:
    runs-on: ubuntu-latest
    outputs:
      is_prerelease: ${{ steps.get_release.outputs.is_prerelease }}
    steps:
      - name: Get release information
        id: get_release
        run: |
          echo "Event name: $GITHUB_EVENT_NAME"  
          echo "Raw prerelease value (release.prerelease):"  
          jq '.release.prerelease' "$GITHUB_EVENT_PATH" || true
          PRERELEASE=$(jq -r '.release.prerelease // false' "$GITHUB_EVENT_PATH")
          echo "Resolved prerelease=$PRERELEASE"
          echo "is_prerelease=$PRERELEASE" >> $GITHUB_OUTPUT

  deploy-preprod:
    needs: check-pre-release
    if: needs.check-pre-release.outputs.is_prerelease == 'true'
    uses: ./.github/workflows/release-solution-to-prod-with-inputs.yml
    with:
      solution_name: ALMLab
    secrets:
      envSecret: ${{ secrets.POWERPLATFORMSPN }}
      BUILD_ENVIRONMENT_URL: ${{ secrets.ENVIRONMENTURL_BUILD }}
      PRODUCTION_ENVIRONMENT_URL: ${{ secrets.ENVIRONMENTURL_PREPROD }}
      CLIENT_ID: ${{ secrets.POWERPLATFORM_APPID }}
      TENANT_ID: ${{ secrets.TENANTID }}

  deploy-prod:
    needs: check-pre-release
    if: needs.check-pre-release.outputs.is_prerelease != 'true'
    uses: ./.github/workflows/release-solution-to-prod-with-inputs.yml
    with:
      solution_name: ALMLab
    secrets:
      envSecret: ${{ secrets.POWERPLATFORMSPN }}
      BUILD_ENVIRONMENT_URL: ${{ secrets.ENVIRONMENTURL_BUILD }}
      # Replace ENVIRONMENTURL_PROD with the actual secret name for your production environment.
      PRODUCTION_ENVIRONMENT_URL: ${{ secrets.ENVIRONMENTURL_PROD }}
      CLIENT_ID: ${{ secrets.POWERPLATFORM_APPID }}
      TENANT_ID: ${{ secrets.TENANTID }}
