name: Action Trigger - On Release
# Call the reusable workflow release-solution-with-inputs.yml
# Release your solution to prod when you create a new release.

on:
  # Automatic release event trigger disabled to prevent auto publishing.
  # Re-enable by uncommenting the following lines:
  # release:
  #   types: [prereleased, released]
  workflow_dispatch:
    inputs:
      solution_name:
        description: 'Solution to release (if running manually)'
        required: true
        type: choice
        options:
          # GENERATED-OPTIONS-START
          - ALMLab
          - TechExcel
          # GENERATED-OPTIONS-END
        # no default; must be specified for manual runs
      target_stage:
        description: 'Target stage to deploy to when running manually'
        required: true
        type: choice
        options:
          - QA
          - PROD
      environment_name:
        description: 'GitHub environment containing ALL required vars/secrets (BUILD + QA + PROD)'
        required: true
        type: choice
        options:
          - philurban-M365x06004729

permissions:
  contents: write

jobs:
  validate-manual:
    if: github.event_name == 'workflow_dispatch' && inputs.solution_name == '<none>'
    runs-on: ubuntu-latest
    steps:
      - name: Fail when placeholder is selected
        run: |
          echo "You must select a real solution name, not <none>." >&2
          exit 1

  manual-deploy:
    if: github.event_name == 'workflow_dispatch' && inputs.solution_name != '<none>'
    uses: ./.github/workflows/release-solution.yml
    with:
      solution_name: ${{ inputs.solution_name }}
      # Using the SAME GitHub environment for both build and target; URLs decide actual platform targets.
      build_environment_name: ${{ inputs.environment_name }}
      target_environment_name: ${{ inputs.environment_name }}
    secrets:
      envSecret: ${{ secrets.POWERPLATFORMAPPSECRET }}
      BUILD_ENVIRONMENT_URL: ${{ vars.ENVIRONMENTURL_BUILD }}
      # Dynamically select target environment URL based on target_stage input
      PRODUCTION_ENVIRONMENT_URL: ${{ inputs.target_stage == 'PROD' && vars.ENVIRONMENTURL_PROD || vars.ENVIRONMENTURL_QA }}
      CLIENT_ID: ${{ secrets.POWERPLATFORMAPPID }}
      TENANT_ID: ${{ secrets.TENANTID }}
