name: Validate Solution Configuration

on:
  push:
    paths:
      - solutions.json
      - solutions/**
      - .github/workflows/*.yml
  pull_request:
    paths:
      - solutions.json
      - solutions/**
      - .github/workflows/*.yml

permissions:
  contents: read

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5
      - name: Validate solutions.json and workflow dropdowns
        shell: bash
        run: |
          set -euo pipefail
          python3 scripts/validate_solutions.py
