name: yaml-lint

on:
  pull_request:
    paths:
      - '**/*.yml'
      - '**/*.yaml'
  push:
    paths:
      - '**/*.yml'
      - '**/*.yaml'
  workflow_dispatch: {}

permissions:
  contents: read

concurrency:
  group: yaml-lint-${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Lint YAML files with yamllint
        uses: ibiqlik/action-yamllint@v3
        with:
          config_file: .yamllint.yaml
          format: github
          file_or_dir: .
          strict: false
